// <auto-generated />
using System;
using EmployeePayrollAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployeePayrollAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260220124332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("EmployeePayrollAPI.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeNumber")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EmployeeNumber");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
